### ISSUE TITLE
What is the appropriate version for SHRED_VERSION

### ISSUE THREAD

**Issue by durch** [solana-labs/solana-bigtable#10]
Documentation mentions updating `SHRED_VERSION` to the appropriate version, having a note in the documentation as to how to find the appropriate version would be very informative

**Comment by davidmehi** [comment]
Run this curl call against your node to get the shredVersion

curl http://localhost:8899 -X POST -H "Content-Type: application/json" -d '
  {"jsonrpc":"2.0", "id":1, "method":"getClusterNodes"}
'
https://docs.solana.com/developing/clients/jsonrpc-api#getclusternodes

**Comment by durch** [comment]
Thank you!
